<a href="https://colab.research.google.com/github/Axle-Bucamp/exploring/blob/main/self_made_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# y^2 + xy + x^2
# df / dx = 2x + y
# df / dy = 2y + x
# grad = 3y + 3x
import numpy as np
import plotly.graph_objects as go

x = [1,2,3,4,5,6,7,8,9,10]
y = [1,2,3,4,5,6,7,8,9,10]

grad = []
for i in range(10):
  arr = []
  for z in range(10):
    arr.append(3 * x[i] + 3 * y[z])
  grad.append(arr)

print(np.array(grad))

fig = go.Figure(data=[go.Surface(z=grad)])

fig.update_layout(title='Gradient Function of y^2 + xy + x^2', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()

[[ 6  9 12 15 18 21 24 27 30 33]
 [ 9 12 15 18 21 24 27 30 33 36]
 [12 15 18 21 24 27 30 33 36 39]
 [15 18 21 24 27 30 33 36 39 42]
 [18 21 24 27 30 33 36 39 42 45]
 [21 24 27 30 33 36 39 42 45 48]
 [24 27 30 33 36 39 42 45 48 51]
 [27 30 33 36 39 42 45 48 51 54]
 [30 33 36 39 42 45 48 51 54 57]
 [33 36 39 42 45 48 51 54 57 60]]


In [ ]:
x =  [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] # [0.5,0.5,1,-1,-0.5,-0.5,0.5,0.2,0.1,3]
y =  [-1,-0.8,-0.6,-0.7,-0.9,-0.5,-0.5,-0.4,-0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4,0.4,0.6,0.5]
len(x)

20

In [ ]:
len(y)

20

In [ ]:
# cost = 1/n sum( ( y - tanh( sum(x*w + b)) )^2 )
# neuron = tanh(sum(x*w + b))

# d cost / dw =  d/w 1/2n sum( ( tanh( sum(x*w + b)) )^2 - y )
## sum rule
## d cost / dw = 1/2n sum( d/dw (u - v)^2 )
### chaine rule
### d cost / dw = 1/2n 2(u - v) *  d/dw (u - v)
### d cost / dw = 1/2n 2(u - v) *  (d/dw u - d/dw v)
### d cost / dw = -1/n (u - v) * (d/dw u)
# and
### d cost / db = -1/n (u - v) * (d/db u)

# d/dw u =  1 - tanh(x)^2
# d/db u =  1 - tanh(1)^2

### gradient = -1/n (u - v) * (d/db u) + -1/n (u - v) * (d/dw u) + 2y


import numpy as np
import plotly.graph_objects as go
import math
x = np.array(x) / 20
grad = []
for i in range(20):
  arr = []
  for z in range(20):
    # x[i] # y[z]
    for w in range(20):
      for b in range(20):
        arr.append(   2*y[z] * (1 - math.tanh(w/20*x[i] + b/20 ) ) * x[i] - ( y[z] - math.tanh( w/20*x[i] + b/20 ) ) *  (1- math.tanh(w/20*x[i] + b/20 )**2 )  )
  grad.append(arr)

fig = go.Figure(data=[go.Surface(z=grad)])

fig.update_layout(title='Gradient Function of sum(y - than(wx+b)^2 )/n', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()
fig.write_html("htmlintegration.html")

In [ ]:
import numpy as np
import plotly.graph_objects as go
import math

### d cost / dw = -1/n (u - v) * (d/dw u)
# and
### d cost / db = -1/n (u - v) * (d/db u)

# d/dw u =  1 - tanh(x)^2
# d/db u =  1 - tanh(1)^2

w = 1
b = 1
train_step = 20
alpha = 0.1
for i in range(train_step):
  y_pred = []
  for i in range(20):
    y_pred.append(math.tanh(w*x[z] + b))

  x = np.array(x)
  y = np.array(y)
  y_pred = np.array(y_pred)
  w = w - alpha * - np.sum( 2* (y-y_pred) * (1 - np.tanh(w*x+b)**2) * x ) /20
  b = b - alpha * - np.sum( 2* (y-y_pred) * (1 - np.tanh(w*x+b)**2) )/20

  alpha = alpha * 0.95
  print("weight : " + str(w) + " bias : " + str(b)  + " error : " + str( np.sum((y- y_pred) * (y - y_pred))/ 40 ) )

weight : 0.9836917265470653 bias : 0.9458061514730081 error : 0.7859099656882018
weight : 0.9664891298850394 bias : 0.8890827576090168 error : 0.7797410376394873
weight : 0.9482974426729901 bias : 0.829595533277089 error : 0.7723493653539223
weight : 0.9290165060096316 bias : 0.767107704556734 error : 0.7634312652521565
weight : 0.9085453218492485 bias : 0.7013960881368757 error : 0.7526002648855958
weight : 0.8867905464799072 bias : 0.63227810395432 error : 0.7393687435149359
weight : 0.8636810780261908 bias : 0.5596545672387596 error : 0.7231324865287923
weight : 0.8391913993856455 bias : 0.48357334337981284 error : 0.7031676489994454
weight : 0.8133760674279172 bias : 0.40431650032601907 error : 0.6786585752946874
weight : 0.7864152988150427 bias : 0.32250520105385916 error : 0.6487867626596786
weight : 0.7586649191339443 bias : 0.23919860919981517 error : 0.6129188449598566
weight : 0.730691892909457 bias : 0.15593659372580343 error : 0.5709143790915455
weight : 0.7032637441606187 

In [ ]:
x =  [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
y =  [-1,-0.8,-0.6,-0.7,-0.9,-0.5,-0.5,-0.4,-0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4,0.4,0.6,0.5]

In [ ]:
# voir corriger l'explosion de gradient ?
import numpy as np
class layer():
  w = []
  b = []
  linearized = []
  activated = []

  graderr = []
  inputvect = []
  derivative = []

  activation = lambda x : x

  def __init__(self, Uactivation,size):
    self.activation = Uactivation
    mu, sigma = 0, 0.1
    self.w = np.random.normal(mu, sigma, size)
    self.b = np.random.normal(mu, sigma, size[0])

  def learn(self,grad, learning_rate,w,):
    self.w = self.w - learning_rate*grad[0]
    self.b = self.b - learning_rate*grad[1]

  def derivate_tanhMethod(self,input):
    self.derivative = np.array(( 1 - np.tanh(self.w.T * input + self.b)**2) * input )
    return self.derivative

  def activate(self,x):
    self.activated = np.array(self.activation(x))
    return self.activated

  def lineare(self,x):
    self.inputvect = x
    self.linearized = np.array(np.sum(self.w.T * x,axis=1) + self.b)
    return self.lineare

  def predict(self,x):
    self.lineare(x)
    return self.activate(self.linearized)

In [ ]:
def train(network, x,y,learning_rate) :
  y_pred = x.copy()
  for layer in network:
    y_pred = layer.predict(y_pred)

  ## learning phase
  print("error : "+ str(np.sum((y -y_pred)**2 )))
  for layer in reversed(range(len(network))):

    if layer == 0:
      network[layer].derivate_tanhMethod(x)
    else :
      network[layer].derivate_tanhMethod(network[layer].activated)

    if layer == len(network) -1:
      network[layer].graderr = network[layer].derivative * (y - y_pred)
    else :
      network[layer].graderr = network[layer].derivative * np.sum(network[layer+1].w * network[layer+1].graderr)

  for layer in range(len(network)):
    if layer == 0:
      network[layer].w = network[layer].w - learning_rate * network[layer].graderr * x
      network[layer].b = network[layer].b - learning_rate * network[layer].graderr * x
    else :
      network[layer].w = network[layer-1].w - learning_rate * network[layer].graderr *network[layer-1].activated
      network[layer].b = network[layer-1].b - learning_rate * network[layer].graderr *network[layer-1].activated

In [ ]:
tanh = lambda x : np.tanh(x)
network = []
# size = (neurone, entrée ), sortie = neurone
network.append(layer(Uactivation=tanh, size=(20,20) ))
network.append(layer(Uactivation=tanh, size=(20,20) ))
network.append(layer(Uactivation=tanh, size=(1,20) ))

train_step = 10
for i in range(train_step):
  train(network, np.array(x),np.array(y)[0], 0.1)

error : 19.890321661241625
error : 29.215138432333625
error : 0.00032976164269736785
error : 0.00020650120065324672
error : 0.0002036286278955985
error : 0.00020063989232554355
error : 0.0001977226854285878
error : 0.00019487413007909126
error : 0.00019209184418294395
error : 0.0001893735630845646
